export { definition as createCredential } from './create-credential/definition'
export { definition as getCredentials } from './get-credentials/definition'
export { definition as updateCredential } from './update-credential/definition'
export { definition as deleteCredential } from './delete-credential/definition'
export { definition as getCredentialSecure } from './get-credential-secure/definition'
